/* tslint:disable */
/* eslint-disable */
/**
 * DomainForge API
 * Enterprise-grade domain intelligence platform API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SafeBigInt } from '../../types/branded';
import { createSafeBigInt } from '../../types/branded';

/**
 * GeneratedDomain represents a domain generated by a domain generation campaign
 * @export
 * @interface ModelsGeneratedDomain
 */
export interface ModelsGeneratedDomain {
    /**
     * 
     * @type {string}
     * @memberof ModelsGeneratedDomain
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGeneratedDomain
     */
    'generationCampaignId': string;
    /**
     * The generated domain name
     * @type {string}
     * @memberof ModelsGeneratedDomain
     */
    'domain': string;
    /**
     * Position in the generation sequence (int64)
     * @type {SafeBigInt}
     * @memberof ModelsGeneratedDomain
     */
    'offsetIndex': SafeBigInt;
    /**
     * When the domain was generated
     * @type {string}
     * @memberof ModelsGeneratedDomain
     */
    'generatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGeneratedDomain
     */
    'createdAt': string;
}

/**
 * Type guard for ModelsGeneratedDomain
 */
export function isModelsGeneratedDomain(value: unknown): value is ModelsGeneratedDomain {
    if (!value || typeof value !== 'object') return false;
    const obj = value as Record<string, unknown>;
    return (
        typeof obj.id === 'string' &&
        typeof obj.generationCampaignId === 'string' &&
        typeof obj.domain === 'string' &&
        typeof obj.offsetIndex === 'bigint' &&
        typeof obj.generatedAt === 'string' &&
        typeof obj.createdAt === 'string'
    );
}

/**
 * Transform raw API response to ModelsGeneratedDomain
 */
export function transformToModelsGeneratedDomain(raw: Record<string, unknown>): ModelsGeneratedDomain {
    const offsetValue = raw.offsetIndex ?? raw.offset_index;
    return {
        id: String(raw.id),
        generationCampaignId: String(raw.generationCampaignId || raw.generation_campaign_id),
        domain: String(raw.domain || raw.domainName || raw.domain_name),
        offsetIndex: createSafeBigInt(offsetValue as string | number | bigint),
        generatedAt: String(raw.generatedAt || raw.generated_at),
        createdAt: String(raw.createdAt || raw.created_at)
    };
}

/**
 * Transform ModelsGeneratedDomain for API request
 */
export function transformFromModelsGeneratedDomain(domain: ModelsGeneratedDomain): Record<string, unknown> {
    return {
        id: domain.id,
        generationCampaignId: domain.generationCampaignId,
        domain: domain.domain,
        offsetIndex: String(domain.offsetIndex),
        generatedAt: domain.generatedAt,
        createdAt: domain.createdAt
    };
}