/* tslint:disable */
 
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-expect-error - API client type compatibility
import type { ModelsUserAPI } from './models-user-api';

/**
 * 
 * @export
 * @interface ModelsLoginResponseAPI
 */
export interface ModelsLoginResponseAPI {
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponseAPI
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponseAPI
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsLoginResponseAPI
     */
    'requires_captcha'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponseAPI
     */
    'sessionId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsLoginResponseAPI
     */
    'success'?: boolean;
    /**
     * 
     * @type {ModelsUserAPI}
     * @memberof ModelsLoginResponseAPI
     */
    'user'?: ModelsUserAPI;
}

