/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SafeBigInt } from '../../types/branded';

/**
 * 
 * @export
 * @interface ServicesDomainGenerationParams
 */
export interface ServicesDomainGenerationParams {
    /**
     * 
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'characterSet': string;
    /**
     * 
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'constantString': string;
    /**
     * 
     * @type {number}
     * @memberof ServicesDomainGenerationParams
     */
    'numDomainsToGenerate'?: number;
    /**
     *
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'patternType': ServicesDomainGenerationParamsPatternTypeEnum;
    /**
     * CRITICAL FIX H-003: Use SafeBigInt for int64 field
     * Backend uses uint64 which can exceed JavaScript's safe integer limit
     * @type {SafeBigInt}
     * @memberof ServicesDomainGenerationParams
     */
    'totalPossibleCombinations'?: SafeBigInt;
    /**
     * CRITICAL FIX H-003: Use SafeBigInt for int64 field
     * Backend uses int64 which can exceed JavaScript's safe integer limit
     * @type {SafeBigInt}
     * @memberof ServicesDomainGenerationParams
     */
    'currentOffset'?: SafeBigInt;
    /**
     * 
     * @type {string}
     * @memberof ServicesDomainGenerationParams
     */
    'tld': string;
    /**
     * 
     * @type {number}
     * @memberof ServicesDomainGenerationParams
     */
    'variableLength': number;
}

export const ServicesDomainGenerationParamsPatternTypeEnum = {
    Prefix: 'prefix',
    Suffix: 'suffix',
    Both: 'both'
} as const;

export type ServicesDomainGenerationParamsPatternTypeEnum = typeof ServicesDomainGenerationParamsPatternTypeEnum[keyof typeof ServicesDomainGenerationParamsPatternTypeEnum];
