/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServicesHttpKeywordParams
 */
export interface ServicesHttpKeywordParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof ServicesHttpKeywordParams
     */
    'adHocKeywords'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ServicesHttpKeywordParams
     */
    'batchSize'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ServicesHttpKeywordParams
     */
    'keywordSetIds'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ServicesHttpKeywordParams
     */
    'personaIds': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ServicesHttpKeywordParams
     */
    'processingSpeedPerMinute'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServicesHttpKeywordParams
     */
    'proxyPoolId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesHttpKeywordParams
     */
    'proxySelectionStrategy'?: string;
    /**
     * 
     * @type {number}
     * @memberof ServicesHttpKeywordParams
     */
    'retryAttempts'?: number;
    /**
     * 
     * @type {number}
     * @memberof ServicesHttpKeywordParams
     */
    'rotationIntervalSeconds'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServicesHttpKeywordParams
     */
    'sourceCampaignId': string;
    /**
     * 
     * @type {string}
     * @memberof ServicesHttpKeywordParams
     */
    'sourceType': ServicesHttpKeywordParamsSourceTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServicesHttpKeywordParams
     */
    'targetHttpPorts'?: Array<number>;
}

export const ServicesHttpKeywordParamsSourceTypeEnum = {
    DomainGeneration: 'DomainGeneration',
    DnsValidation: 'DNSValidation'
} as const;

export type ServicesHttpKeywordParamsSourceTypeEnum = typeof ServicesHttpKeywordParamsSourceTypeEnum[keyof typeof ServicesHttpKeywordParamsSourceTypeEnum];
