/* tslint:disable */
/* eslint-disable */
/**
 * DomainFlow API
 * DomainFlow API for domain generation, validation, and campaign management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@domainflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ServicesDnsValidationParams } from './services-dns-validation-params';
// May contain unused imports in some cases
// @ts-ignore
import type { ServicesDomainGenerationParams } from './services-domain-generation-params';
// May contain unused imports in some cases
// @ts-ignore
import type { ServicesHttpKeywordParams } from './services-http-keyword-params';

/**
 * 
 * @export
 * @interface ServicesCreateCampaignRequest
 */
export interface ServicesCreateCampaignRequest {
    /**
     * 
     * @type {string}
     * @memberof ServicesCreateCampaignRequest
     */
    'campaignType': ServicesCreateCampaignRequestCampaignTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ServicesCreateCampaignRequest
     */
    'description'?: string;
    /**
     * DNS Validation specific fields
     * @type {ServicesDnsValidationParams}
     * @memberof ServicesCreateCampaignRequest
     */
    'dnsValidationParams'?: ServicesDnsValidationParams;
    /**
     * Domain Generation specific fields
     * @type {ServicesDomainGenerationParams}
     * @memberof ServicesCreateCampaignRequest
     */
    'domainGenerationParams'?: ServicesDomainGenerationParams;
    /**
     * HTTP Keyword Validation specific fields
     * @type {ServicesHttpKeywordParams}
     * @memberof ServicesCreateCampaignRequest
     */
    'httpKeywordParams'?: ServicesHttpKeywordParams;
    /**
     * 
     * @type {string}
     * @memberof ServicesCreateCampaignRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ServicesCreateCampaignRequest
     */
    'userId'?: string;
}

export const ServicesCreateCampaignRequestCampaignTypeEnum = {
    DomainGeneration: 'domain_generation',
    DnsValidation: 'dns_validation',
    HttpKeywordValidation: 'http_keyword_validation'
} as const;

export type ServicesCreateCampaignRequestCampaignTypeEnum = typeof ServicesCreateCampaignRequestCampaignTypeEnum[keyof typeof ServicesCreateCampaignRequestCampaignTypeEnum];


