name: API Contract Validation

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'backend/docs/openapi.json'
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
  validate-contracts:
    runs-on: ubuntu-latest
    name: Validate API Contracts
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Go Swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest
        
      - name: Build backend (validate compilation)
        run: |
          cd backend
          go mod tidy
          go build ./cmd/apiserver
          
      - name: Validate API contracts
        run: npm run api:validate
        
      - name: Comment on PR (if validation fails)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **API Contract Validation Failed**\n\nThe backend API changes don\'t match the committed OpenAPI specification.\n\nPlease run `npm run api:generate` to update the contracts, or revert unintended backend changes.\n\nSee the CI logs for detailed differences.'
            });
            
  generate-client-check:
    runs-on: ubuntu-latest
    name: Verify Generated Client is Up-to-Date
    needs: validate-contracts
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Java (for OpenAPI generator)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate fresh TypeScript client
        run: npm run api:generate-client
        
      - name: Check if generated client differs
        run: |
          if git diff --exit-code src/lib/api-client/; then
            echo "✅ Generated TypeScript client is up-to-date"
          else
            echo "❌ Generated TypeScript client differs from committed version"
            echo "Please run 'npm run api:generate' and commit the changes"
            git diff src/lib/api-client/
            exit 1
          fi
